./openssl s_server -key /root/server.key -cert /root/server.crt -accept 443 -cipher $1  -WWW -tls1_1 &
./openssl s_server -key /root/server.key -cert /root/server.crt -accept 989 -cipher $1  -WWW -tls1_1 &
./openssl s_server -key /root/server.key -cert /root/server.crt -accept 990 -cipher $1  -WWW -tls1_1 &
./openssl s_server -key /root/server.key -cert /root/server.crt -accept 992 -cipher $1  -WWW -tls1_1 &
./openssl s_server -key /root/server.key -cert /root/server.crt -accept 993 -cipher $1  -WWW -tls1_1 &
./openssl s_server -key /root/server.key -cert /root/server.crt -accept 994 -cipher $1  -WWW -tls1_1 &
./openssl s_server -key /root/server.key -cert /root/server.crt -accept 995 -cipher $1  -WWW -tls1_1 &
./openssl s_server -key /root/server.key -cert /root/server.crt -accept 1364 -cipher $1  -WWW -tls1_1 &
./openssl s_server -key /root/server.key -cert /root/server.crt -accept 4116 -cipher $1  -WWW -tls1_1 &
./openssl s_server -key /root/server.key -cert /root/server.crt -accept 5349 -cipher $1  -WWW -tls1_1 &
./openssl s_server -key /root/server.key -cert /root/server.crt -accept 6514 -cipher $1  -WWW -tls1_1 &
./openssl s_server -key /root/server.key -cert /root/server.crt -accept 8531 -cipher $1  -WWW -tls1_1 &
./openssl s_server -key /root/server.key -cert /root/server.crt -accept 1001 -cipher $1  -WWW -tls1_1 &
./openssl s_server -key /root/server.key -cert /root/server.crt -accept 1002 -cipher $1  -WWW -tls1_1 &
./openssl s_server -key /root/server.key -cert /root/server.crt -accept 1003 -cipher $1  -WWW -tls1_1 &
./openssl s_server -key /root/server.key -cert /root/server.crt -accept 1004 -cipher $1  -WWW -tls1_1 &
./openssl s_server -key /root/server.key -cert /root/server.crt -accept 1005 -cipher $1  -WWW -tls1_1 &
./openssl s_server -key /root/server.key -cert /root/server.crt -accept 1006 -cipher $1  -WWW -tls1_1 &
./openssl s_server -key /root/server.key -cert /root/server.crt -accept 1007 -cipher $1  -WWW -tls1_1 &
./openssl s_server -key /root/server.key -cert /root/server.crt -accept 1008 -cipher $1  -WWW -tls1_1 &
./openssl s_server -key /root/server.key -cert /root/server.crt -accept 1009 -cipher $1  -WWW -tls1_1 &
./openssl s_server -key /root/server.key -cert /root/server.crt -accept 1010 -cipher $1  -WWW -tls1_1 &
./openssl s_server -key /root/server.key -cert /root/server.crt -accept 1011 -cipher $1  -WWW -tls1_1 &
./openssl s_server -key /root/server.key -cert /root/server.crt -accept 1012 -cipher $1  -WWW -tls1_1 &
./openssl s_server -key /root/server.key -cert /root/server.crt -accept 1013 -cipher $1  -WWW -tls1_1 &
./openssl s_server -key /root/server.key -cert /root/server.crt -accept 1014 -cipher $1  -WWW -tls1_1 &
./openssl s_server -key /root/server.key -cert /root/server.crt -accept 1015 -cipher $1  -WWW -tls1_1 &
./openssl s_server -key /root/server.key -cert /root/server.crt -accept 1016 -cipher $1  -WWW -tls1_1 &
./openssl s_server -key /root/server.key -cert /root/server.crt -accept 1017 -cipher $1  -WWW -tls1_1 &
./openssl s_server -key /root/server.key -cert /root/server.crt -accept 1018 -cipher $1  -WWW -tls1_1 &
./openssl s_server -key /root/server.key -cert /root/server.crt -accept 1019 -cipher $1  -WWW -tls1_1 &
./openssl s_server -key /root/server.key -cert /root/server.crt -accept 1020 -cipher $1  -WWW -tls1_1 &
./openssl s_server -key /root/server.key -cert /root/server.crt -accept 1021 -cipher $1  -WWW -tls1_1 &
./openssl s_server -key /root/server.key -cert /root/server.crt -accept 1022 -cipher $1  -WWW -tls1_1 &
./openssl s_server -key /root/server.key -cert /root/server.crt -accept 1023 -cipher $1  -WWW -tls1_1 &
./openssl s_server -key /root/server.key -cert /root/server.crt -accept 1024 -cipher $1  -WWW -tls1_1 &
./openssl s_server -key /root/server.key -cert /root/server.crt -accept 1025 -cipher $1  -WWW -tls1_1 &
./openssl s_server -key /root/server.key -cert /root/server.crt -accept 1026 -cipher $1  -WWW -tls1_1 &
./openssl s_server -key /root/server.key -cert /root/server.crt -accept 1027 -cipher $1  -WWW -tls1_1 &
./openssl s_server -key /root/server.key -cert /root/server.crt -accept 1028 -cipher $1  -WWW -tls1_1 &
./openssl s_server -key /root/server.key -cert /root/server.crt -accept 1029 -cipher $1  -WWW -tls1_1 &
./openssl s_server -key /root/server.key -cert /root/server.crt -accept 1030 -cipher $1  -WWW -tls1_1 &
./openssl s_server -key /root/server.key -cert /root/server.crt -accept 1031 -cipher $1  -WWW -tls1_1 &
./openssl s_server -key /root/server.key -cert /root/server.crt -accept 1032 -cipher $1  -WWW -tls1_1 &
./openssl s_server -key /root/server.key -cert /root/server.crt -accept 1033 -cipher $1  -WWW -tls1_1 &
./openssl s_server -key /root/server.key -cert /root/server.crt -accept 1034 -cipher $1  -WWW -tls1_1 &
./openssl s_server -key /root/server.key -cert /root/server.crt -accept 1035 -cipher $1  -WWW -tls1_1 &
./openssl s_server -key /root/server.key -cert /root/server.crt -accept 1036 -cipher $1  -WWW -tls1_1 &
./openssl s_server -key /root/server.key -cert /root/server.crt -accept 1037 -cipher $1  -WWW -tls1_1 &
./openssl s_server -key /root/server.key -cert /root/server.crt -accept 1038 -cipher $1  -WWW -tls1_1 &
./openssl s_server -key /root/server.key -cert /root/server.crt -accept 1039 -cipher $1  -WWW -tls1_1 &
./openssl s_server -key /root/server.key -cert /root/server.crt -accept 1040 -cipher $1  -WWW -tls1_1 &
./openssl s_server -key /root/server.key -cert /root/server.crt -accept 1041 -cipher $1  -WWW -tls1_1 &
./openssl s_server -key /root/server.key -cert /root/server.crt -accept 1042 -cipher $1  -WWW -tls1_1 &
./openssl s_server -key /root/server.key -cert /root/server.crt -accept 1043 -cipher $1  -WWW -tls1_1 &
./openssl s_server -key /root/server.key -cert /root/server.crt -accept 1044 -cipher $1  -WWW -tls1_1 &
./openssl s_server -key /root/server.key -cert /root/server.crt -accept 1045 -cipher $1  -WWW -tls1_1 &
./openssl s_server -key /root/server.key -cert /root/server.crt -accept 1046 -cipher $1  -WWW -tls1_1 &
./openssl s_server -key /root/server.key -cert /root/server.crt -accept 1047 -cipher $1  -WWW -tls1_1 &
./openssl s_server -key /root/server.key -cert /root/server.crt -accept 1048 -cipher $1  -WWW -tls1_1 &
./openssl s_server -key /root/server.key -cert /root/server.crt -accept 1049 -cipher $1  -WWW -tls1_1 &
./openssl s_server -key /root/server.key -cert /root/server.crt -accept 1050 -cipher $1  -WWW -tls1_1 &
./openssl s_server -key /root/server.key -cert /root/server.crt -accept 1051 -cipher $1  -WWW -tls1_1 &
./openssl s_server -key /root/server.key -cert /root/server.crt -accept 1052 -cipher $1  -WWW -tls1_1 &
./openssl s_server -key /root/server.key -cert /root/server.crt -accept 1053 -cipher $1  -WWW -tls1_1 &
./openssl s_server -key /root/server.key -cert /root/server.crt -accept 1054 -cipher $1  -WWW -tls1_1 &
./openssl s_server -key /root/server.key -cert /root/server.crt -accept 1055 -cipher $1  -WWW -tls1_1 &
./openssl s_server -key /root/server.key -cert /root/server.crt -accept 1056 -cipher $1  -WWW -tls1_1 &
./openssl s_server -key /root/server.key -cert /root/server.crt -accept 1057 -cipher $1  -WWW -tls1_1 &
./openssl s_server -key /root/server.key -cert /root/server.crt -accept 1058 -cipher $1  -WWW -tls1_1 &
./openssl s_server -key /root/server.key -cert /root/server.crt -accept 1059 -cipher $1  -WWW -tls1_1 &
./openssl s_server -key /root/server.key -cert /root/server.crt -accept 1060 -cipher $1  -WWW -tls1_1 &
./openssl s_server -key /root/server.key -cert /root/server.crt -accept 1061 -cipher $1  -WWW -tls1_1 &
./openssl s_server -key /root/server.key -cert /root/server.crt -accept 1062 -cipher $1  -WWW -tls1_1 &
./openssl s_server -key /root/server.key -cert /root/server.crt -accept 1063 -cipher $1  -WWW -tls1_1 &
./openssl s_server -key /root/server.key -cert /root/server.crt -accept 1064 -cipher $1  -WWW -tls1_1 &
./openssl s_server -key /root/server.key -cert /root/server.crt -accept 1065 -cipher $1  -WWW -tls1_1 &
./openssl s_server -key /root/server.key -cert /root/server.crt -accept 1066 -cipher $1  -WWW -tls1_1 &
./openssl s_server -key /root/server.key -cert /root/server.crt -accept 1067 -cipher $1  -WWW -tls1_1 &
./openssl s_server -key /root/server.key -cert /root/server.crt -accept 1068 -cipher $1  -WWW -tls1_1 &
./openssl s_server -key /root/server.key -cert /root/server.crt -accept 1069 -cipher $1  -WWW -tls1_1 &
./openssl s_server -key /root/server.key -cert /root/server.crt -accept 1070 -cipher $1  -WWW -tls1_1 &
./openssl s_server -key /root/server.key -cert /root/server.crt -accept 1071 -cipher $1  -WWW -tls1_1 &
./openssl s_server -key /root/server.key -cert /root/server.crt -accept 1072 -cipher $1  -WWW -tls1_1 &
./openssl s_server -key /root/server.key -cert /root/server.crt -accept 1073 -cipher $1  -WWW -tls1_1 &
./openssl s_server -key /root/server.key -cert /root/server.crt -accept 1074 -cipher $1  -WWW -tls1_1 &
./openssl s_server -key /root/server.key -cert /root/server.crt -accept 1075 -cipher $1  -WWW -tls1_1 &
./openssl s_server -key /root/server.key -cert /root/server.crt -accept 1076 -cipher $1  -WWW -tls1_1 &
./openssl s_server -key /root/server.key -cert /root/server.crt -accept 1077 -cipher $1  -WWW -tls1_1 &
./openssl s_server -key /root/server.key -cert /root/server.crt -accept 1078 -cipher $1  -WWW -tls1_1 &
./openssl s_server -key /root/server.key -cert /root/server.crt -accept 1079 -cipher $1  -WWW -tls1_1 &
./openssl s_server -key /root/server.key -cert /root/server.crt -accept 1080 -cipher $1  -WWW -tls1_1 &
./openssl s_server -key /root/server.key -cert /root/server.crt -accept 1081 -cipher $1  -WWW -tls1_1 &
./openssl s_server -key /root/server.key -cert /root/server.crt -accept 1082 -cipher $1  -WWW -tls1_1 &
./openssl s_server -key /root/server.key -cert /root/server.crt -accept 1083 -cipher $1  -WWW -tls1_1 &
./openssl s_server -key /root/server.key -cert /root/server.crt -accept 1084 -cipher $1  -WWW -tls1_1 &
./openssl s_server -key /root/server.key -cert /root/server.crt -accept 1085 -cipher $1  -WWW -tls1_1 &
./openssl s_server -key /root/server.key -cert /root/server.crt -accept 1086 -cipher $1  -WWW -tls1_1 &
./openssl s_server -key /root/server.key -cert /root/server.crt -accept 1087 -cipher $1  -WWW -tls1_1 &
./openssl s_server -key /root/server.key -cert /root/server.crt -accept 1088 -cipher $1  -WWW -tls1_1 &
./openssl s_server -key /root/server.key -cert /root/server.crt -accept 1089 -cipher $1  -WWW -tls1_1 &
./openssl s_server -key /root/server.key -cert /root/server.crt -accept 1090 -cipher $1  -WWW -tls1_1 &
./openssl s_server -key /root/server.key -cert /root/server.crt -accept 1091 -cipher $1  -WWW -tls1_1 &
./openssl s_server -key /root/server.key -cert /root/server.crt -accept 1092 -cipher $1  -WWW -tls1_1 &
./openssl s_server -key /root/server.key -cert /root/server.crt -accept 1093 -cipher $1  -WWW -tls1_1 &
./openssl s_server -key /root/server.key -cert /root/server.crt -accept 1094 -cipher $1  -WWW -tls1_1 &
./openssl s_server -key /root/server.key -cert /root/server.crt -accept 1095 -cipher $1  -WWW -tls1_1 &
./openssl s_server -key /root/server.key -cert /root/server.crt -accept 1096 -cipher $1  -WWW -tls1_1 &
./openssl s_server -key /root/server.key -cert /root/server.crt -accept 1097 -cipher $1  -WWW -tls1_1 &
./openssl s_server -key /root/server.key -cert /root/server.crt -accept 1098 -cipher $1  -WWW -tls1_1 &
./openssl s_server -key /root/server.key -cert /root/server.crt -accept 1099 -cipher $1  -WWW -tls1_1 &
./openssl s_server -key /root/server.key -cert /root/server.crt -accept 1100 -cipher $1  -WWW -tls1_1 &
./openssl s_server -key /root/server.key -cert /root/server.crt -accept 1101 -cipher $1  -WWW -tls1_1 &
./openssl s_server -key /root/server.key -cert /root/server.crt -accept 1102 -cipher $1  -WWW -tls1_1 &
./openssl s_server -key /root/server.key -cert /root/server.crt -accept 1103 -cipher $1  -WWW -tls1_1 &
./openssl s_server -key /root/server.key -cert /root/server.crt -accept 1104 -cipher $1  -WWW -tls1_1 &
./openssl s_server -key /root/server.key -cert /root/server.crt -accept 1105 -cipher $1  -WWW -tls1_1 &
./openssl s_server -key /root/server.key -cert /root/server.crt -accept 1106 -cipher $1  -WWW -tls1_1 &
./openssl s_server -key /root/server.key -cert /root/server.crt -accept 1107 -cipher $1  -WWW -tls1_1 &
./openssl s_server -key /root/server.key -cert /root/server.crt -accept 1108 -cipher $1  -WWW -tls1_1 &
./openssl s_server -key /root/server.key -cert /root/server.crt -accept 1109 -cipher $1  -WWW -tls1_1 &
./openssl s_server -key /root/server.key -cert /root/server.crt -accept 1110 -cipher $1  -WWW -tls1_1 &
./openssl s_server -key /root/server.key -cert /root/server.crt -accept 1111 -cipher $1  -WWW -tls1_1 &
./openssl s_server -key /root/server.key -cert /root/server.crt -accept 1112 -cipher $1  -WWW -tls1_1 &
./openssl s_server -key /root/server.key -cert /root/server.crt -accept 1113 -cipher $1  -WWW -tls1_1 &
./openssl s_server -key /root/server.key -cert /root/server.crt -accept 1114 -cipher $1  -WWW -tls1_1 &
./openssl s_server -key /root/server.key -cert /root/server.crt -accept 1115 -cipher $1  -WWW -tls1_1 &
./openssl s_server -key /root/server.key -cert /root/server.crt -accept 1116 -cipher $1  -WWW -tls1_1 &
./openssl s_server -key /root/server.key -cert /root/server.crt -accept 1117 -cipher $1  -WWW -tls1_1 &
./openssl s_server -key /root/server.key -cert /root/server.crt -accept 1118 -cipher $1  -WWW -tls1_1 &
./openssl s_server -key /root/server.key -cert /root/server.crt -accept 1119 -cipher $1  -WWW -tls1_1 &
./openssl s_server -key /root/server.key -cert /root/server.crt -accept 1120 -cipher $1  -WWW -tls1_1 &
./openssl s_server -key /root/server.key -cert /root/server.crt -accept 1121 -cipher $1  -WWW -tls1_1 &
./openssl s_server -key /root/server.key -cert /root/server.crt -accept 1122 -cipher $1  -WWW -tls1_1 &
./openssl s_server -key /root/server.key -cert /root/server.crt -accept 1123 -cipher $1  -WWW -tls1_1 &
./openssl s_server -key /root/server.key -cert /root/server.crt -accept 1124 -cipher $1  -WWW -tls1_1 &
./openssl s_server -key /root/server.key -cert /root/server.crt -accept 1125 -cipher $1  -WWW -tls1_1 &
./openssl s_server -key /root/server.key -cert /root/server.crt -accept 1126 -cipher $1  -WWW -tls1_1 &
./openssl s_server -key /root/server.key -cert /root/server.crt -accept 1127 -cipher $1  -WWW -tls1_1 &
./openssl s_server -key /root/server.key -cert /root/server.crt -accept 1128 -cipher $1  -WWW -tls1_1 &
./openssl s_server -key /root/server.key -cert /root/server.crt -accept 1129 -cipher $1  -WWW -tls1_1 &
./openssl s_server -key /root/server.key -cert /root/server.crt -accept 1130 -cipher $1  -WWW -tls1_1 &
./openssl s_server -key /root/server.key -cert /root/server.crt -accept 1131 -cipher $1  -WWW -tls1_1 &
./openssl s_server -key /root/server.key -cert /root/server.crt -accept 1132 -cipher $1  -WWW -tls1_1 &
./openssl s_server -key /root/server.key -cert /root/server.crt -accept 1133 -cipher $1  -WWW -tls1_1 &
./openssl s_server -key /root/server.key -cert /root/server.crt -accept 1134 -cipher $1  -WWW -tls1_1 &
./openssl s_server -key /root/server.key -cert /root/server.crt -accept 1135 -cipher $1  -WWW -tls1_1 &
./openssl s_server -key /root/server.key -cert /root/server.crt -accept 1136 -cipher $1  -WWW -tls1_1 &
./openssl s_server -key /root/server.key -cert /root/server.crt -accept 1137 -cipher $1  -WWW -tls1_1 &
./openssl s_server -key /root/server.key -cert /root/server.crt -accept 1138 -cipher $1  -WWW -tls1_1 &
./openssl s_server -key /root/server.key -cert /root/server.crt -accept 1139 -cipher $1  -WWW -tls1_1 &
./openssl s_server -key /root/server.key -cert /root/server.crt -accept 1140 -cipher $1  -WWW -tls1_1 &
./openssl s_server -key /root/server.key -cert /root/server.crt -accept 1141 -cipher $1  -WWW -tls1_1 &
./openssl s_server -key /root/server.key -cert /root/server.crt -accept 1142 -cipher $1  -WWW -tls1_1 &
./openssl s_server -key /root/server.key -cert /root/server.crt -accept 1143 -cipher $1  -WWW -tls1_1 &
./openssl s_server -key /root/server.key -cert /root/server.crt -accept 1144 -cipher $1  -WWW -tls1_1 &
./openssl s_server -key /root/server.key -cert /root/server.crt -accept 1145 -cipher $1  -WWW -tls1_1 &
./openssl s_server -key /root/server.key -cert /root/server.crt -accept 1146 -cipher $1  -WWW -tls1_1 &
./openssl s_server -key /root/server.key -cert /root/server.crt -accept 1147 -cipher $1  -WWW -tls1_1 &
./openssl s_server -key /root/server.key -cert /root/server.crt -accept 1148 -cipher $1  -WWW -tls1_1 &
./openssl s_server -key /root/server.key -cert /root/server.crt -accept 1149 -cipher $1  -WWW -tls1_1 &
./openssl s_server -key /root/server.key -cert /root/server.crt -accept 1150 -cipher $1  -WWW -tls1_1 &
./openssl s_server -key /root/server.key -cert /root/server.crt -accept 1151 -cipher $1  -WWW -tls1_1 &
./openssl s_server -key /root/server.key -cert /root/server.crt -accept 1152 -cipher $1  -WWW -tls1_1 &
./openssl s_server -key /root/server.key -cert /root/server.crt -accept 1153 -cipher $1  -WWW -tls1_1 &
./openssl s_server -key /root/server.key -cert /root/server.crt -accept 1154 -cipher $1  -WWW -tls1_1 &
./openssl s_server -key /root/server.key -cert /root/server.crt -accept 1155 -cipher $1  -WWW -tls1_1 &
./openssl s_server -key /root/server.key -cert /root/server.crt -accept 1156 -cipher $1  -WWW -tls1_1 &
./openssl s_server -key /root/server.key -cert /root/server.crt -accept 1157 -cipher $1  -WWW -tls1_1 &
./openssl s_server -key /root/server.key -cert /root/server.crt -accept 1158 -cipher $1  -WWW -tls1_1 &
./openssl s_server -key /root/server.key -cert /root/server.crt -accept 1159 -cipher $1  -WWW -tls1_1 &
./openssl s_server -key /root/server.key -cert /root/server.crt -accept 1160 -cipher $1  -WWW -tls1_1 &
./openssl s_server -key /root/server.key -cert /root/server.crt -accept 1161 -cipher $1  -WWW -tls1_1 &
./openssl s_server -key /root/server.key -cert /root/server.crt -accept 1162 -cipher $1  -WWW -tls1_1 &
./openssl s_server -key /root/server.key -cert /root/server.crt -accept 1163 -cipher $1  -WWW -tls1_1 &
./openssl s_server -key /root/server.key -cert /root/server.crt -accept 1164 -cipher $1  -WWW -tls1_1 &
./openssl s_server -key /root/server.key -cert /root/server.crt -accept 1165 -cipher $1  -WWW -tls1_1 &
./openssl s_server -key /root/server.key -cert /root/server.crt -accept 1166 -cipher $1  -WWW -tls1_1 &
./openssl s_server -key /root/server.key -cert /root/server.crt -accept 1167 -cipher $1  -WWW -tls1_1 &
./openssl s_server -key /root/server.key -cert /root/server.crt -accept 1168 -cipher $1  -WWW -tls1_1 &
./openssl s_server -key /root/server.key -cert /root/server.crt -accept 1169 -cipher $1  -WWW -tls1_1 &
./openssl s_server -key /root/server.key -cert /root/server.crt -accept 1170 -cipher $1  -WWW -tls1_1 &
./openssl s_server -key /root/server.key -cert /root/server.crt -accept 1171 -cipher $1  -WWW -tls1_1 &
./openssl s_server -key /root/server.key -cert /root/server.crt -accept 1172 -cipher $1  -WWW -tls1_1 &
./openssl s_server -key /root/server.key -cert /root/server.crt -accept 1173 -cipher $1  -WWW -tls1_1 &
./openssl s_server -key /root/server.key -cert /root/server.crt -accept 1174 -cipher $1  -WWW -tls1_1 &
./openssl s_server -key /root/server.key -cert /root/server.crt -accept 1175 -cipher $1  -WWW -tls1_1 &
./openssl s_server -key /root/server.key -cert /root/server.crt -accept 1176 -cipher $1  -WWW -tls1_1 &
./openssl s_server -key /root/server.key -cert /root/server.crt -accept 1177 -cipher $1  -WWW -tls1_1 &
./openssl s_server -key /root/server.key -cert /root/server.crt -accept 1178 -cipher $1  -WWW -tls1_1 &
./openssl s_server -key /root/server.key -cert /root/server.crt -accept 1179 -cipher $1  -WWW -tls1_1 &
./openssl s_server -key /root/server.key -cert /root/server.crt -accept 1180 -cipher $1  -WWW -tls1_1 &
./openssl s_server -key /root/server.key -cert /root/server.crt -accept 1181 -cipher $1  -WWW -tls1_1 &
./openssl s_server -key /root/server.key -cert /root/server.crt -accept 1182 -cipher $1  -WWW -tls1_1 &
./openssl s_server -key /root/server.key -cert /root/server.crt -accept 1183 -cipher $1  -WWW -tls1_1 &
./openssl s_server -key /root/server.key -cert /root/server.crt -accept 1184 -cipher $1  -WWW -tls1_1 &
./openssl s_server -key /root/server.key -cert /root/server.crt -accept 1185 -cipher $1  -WWW -tls1_1 &
./openssl s_server -key /root/server.key -cert /root/server.crt -accept 1186 -cipher $1  -WWW -tls1_1 &
./openssl s_server -key /root/server.key -cert /root/server.crt -accept 1187 -cipher $1  -WWW -tls1_1 &
./openssl s_server -key /root/server.key -cert /root/server.crt -accept 1188 -cipher $1  -WWW -tls1_1 &
./openssl s_server -key /root/server.key -cert /root/server.crt -accept 1189 -cipher $1  -WWW -tls1_1 &
./openssl s_server -key /root/server.key -cert /root/server.crt -accept 1190 -cipher $1  -WWW -tls1_1 &
./openssl s_server -key /root/server.key -cert /root/server.crt -accept 1191 -cipher $1  -WWW -tls1_1 &
./openssl s_server -key /root/server.key -cert /root/server.crt -accept 1192 -cipher $1  -WWW -tls1_1 &
./openssl s_server -key /root/server.key -cert /root/server.crt -accept 1193 -cipher $1  -WWW -tls1_1 &
./openssl s_server -key /root/server.key -cert /root/server.crt -accept 1194 -cipher $1  -WWW -tls1_1 &
./openssl s_server -key /root/server.key -cert /root/server.crt -accept 1195 -cipher $1  -WWW -tls1_1 &
./openssl s_server -key /root/server.key -cert /root/server.crt -accept 1196 -cipher $1  -WWW -tls1_1 &
./openssl s_server -key /root/server.key -cert /root/server.crt -accept 1197 -cipher $1  -WWW -tls1_1 &
./openssl s_server -key /root/server.key -cert /root/server.crt -accept 1198 -cipher $1  -WWW -tls1_1 &
./openssl s_server -key /root/server.key -cert /root/server.crt -accept 1199 -cipher $1  -WWW -tls1_1 &
./openssl s_server -key /root/server.key -cert /root/server.crt -accept 1200 -cipher $1  -WWW -tls1_1 &
